"""conversation personas

Revision ID: 3a57a68dc742
Revises: 3fce4a4a6ed7
Create Date: 2026-09-18 21:10:53.430968
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3a57a68dc742'
down_revision = '3fce4a4a6ed7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('system_prompt')
        batch_op.drop_column('persona')

    # ### end Alembic commands ###
